<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register - BK FOOD</title>
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <link rel="icon" type="image/png" href="{{ asset('images/favicon-32x32.png') }}">

</head>
<body>
    <div class="auth-container">
        <div class="auth-form">
            <img src="{{ asset('images/bk-food.png') }}" alt="BK FOOD Logo" class="logo">
            <form method="POST" action="{{ route('register') }}">
                @csrf
                <h2>Register</h2>

                @if ($errors->any())
                <div class="alert">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                <!-- Name Field -->
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" id="name" name="name" required autofocus>
                </div>

                <!-- Email Field -->
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" required>
                </div>

                <!-- MLE Field (Hidden) -->
                <input type="hidden" id="MLE" name="MLE" value="{{ session('autoGeneratedMLE') }}">

                <!-- Direction Field -->
                <div class="form-group">
                    <label for="direction">Direction:</label>
                    <input type="text" id="direction" name="direction" required>
                </div>

                <!-- Supervisor Name Field -->
                <div class="form-group">
                    <label for="supervisor">Supervisor Name:</label>
                    <input type="text" id="supervisor" name="supervisor" required>
                </div>

                <!-- Affectation Field -->
                <div class="form-group">
                    <label for="affectation">Affectation:</label>
                    <input type="text" id="affectation" name="affectation" required>
                </div>

                <!-- Password Field -->
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" id="password" name="password" required>
                </div>

                <!-- Confirm Password Field -->
                <div class="form-group">
                    <label for="password_confirmation">Confirm Password:</label>
                    <input type="password" id="password_confirmation" name="password_confirmation" required>
                </div>

                <button type="submit" class="btn">Register</button>
                <p>Already have an account? <a href="{{ route('login') }}">Login</a></p>
            </form>
        </div>
    </div>
</body>
</html>
